user_service:
  addr: xds:///user:5000
wallet_service:
  addr: xds:///wallet:5000

general:
  initial_balance: 100

new_user_consumer:
  addrs: [ "kafka:9092" ]
  version: 3.6.0
  topic: new_user_event
  consumer_group: event_handler

new_transaction_consumer:
  addrs: [ "kafka:9092" ]
  version: 3.6.0
  topic: new_transaction_event
  consumer_group: event_handler
