apiVersion: v1
kind: Service

metadata:
  name: wallet
  annotations:
    goldenpay.prometheus/scrape: "true"
    goldenpay.prometheus/path: "/metrics"
    goldenpay.prometheus/port: "5050"
spec:
  ports:
    - port: 5000
      name: service
    - port: 5050
      name: metric
  selector:
    app: goldenpay
    name: wallet
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldenpay-be-deployment-wallet
  labels:
    app: goldenpay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goldenpay
      tier: be
  template:
    metadata:
      labels:
        app: goldenpay
        name: wallet
        tier: be
    spec:
      containers:
        - name: goldenpay-wallet
          image: chientt1993/goldenpay-be-wallet
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
