apiVersion: v1
kind: Service

metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: goldenpay
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql
  labels:
    tier: middleware

spec:
  selector:
    matchLabels:
      app: goldenpay
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: goldenpay
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-ps
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-ps
          persistentVolumeClaim:
            claimName: mysql-pv-claim