# TODO use pv
apiVersion: v1
kind: Service
metadata:
  labels:
    app: goldenpay
  name: zookeeper
spec:
  ports:
    - port: 2181
  selector:
    app: goldenpay
    name: zookeeper
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: goldenpay
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goldenpay
  template:
    metadata:
      labels:
        app: goldenpay
        name: zookeeper
    spec:
      containers:
        - image: bitnami/zookeeper:3.6.0
          name: zookeeper
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"