apiVersion: v1
kind: Service

metadata:
  name: event-handler
  annotations:
    goldenpay.prometheus/scrape: "true"
    goldenpay.prometheus/path: "/metrics"
    goldenpay.prometheus/port: "5050"
spec:
  ports:
    - port: 5000
      name: grpc
    - port: 5050
      name: metric
  selector:
    app: goldenpay
    name: event-handler
#  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldenpay-be-deployment-event-handler
  labels:
    app: goldenpay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goldenpay
      tier: be
  template:
    metadata:
      annotations:
        inject.istio.io/templates: grpc-agent
        proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'
      labels:
        app: goldenpay
        name: event-handler
        tier: be
        version: v1
    spec:
      containers:
        - name: goldenpay-event-handler
          image: chientt1993/goldenpay-be-event-handler
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: event-handler
spec:
  hosts:
  - event-handler
  http:
  - match:
    - port: 5000
    route:
    - destination:
        host: event-handler
        subset: v1

---
# DestinationRule
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: event-handler
spec:
  host: event-handler
  subsets:
  - name: v1
    labels:
      version: v1