db:
  addr: mysql:3306
  user: root
  pass: root
  db_name: golden_pay_db

wallet_service:
  addr: :5000

new_transaction_producer:
  addrs: ["kafka:9092"]
  version: 3.6.0
  topic: new_transaction_event
