db:
  addr: localhost:53306
  user: root
  pass: root
  db_name: golden_pay_db

wallet_service:
  addr: localhost:5002

new_transaction_producer:
  addrs: ["localhost:59092"]
  version: 3.6.0
  topic: new_transaction_event
