apiVersion: v1
kind: Service

metadata:
  name: __service
  annotations:
    goldenpay.prometheus/scrape: "true"
    goldenpay.prometheus/path: "/metrics"
    goldenpay.prometheus/port: "5050"
spec:
  ports:
    - port: 5000
      name: grpc
    - port: 5050
      name: metric
  selector:
    app: goldenpay
    name: __service
#  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldenpay-be-deployment-__service
  labels:
    app: goldenpay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goldenpay
      tier: be
  template:
    metadata:
      annotations:
        inject.istio.io/templates: grpc-agent
        proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'
      labels:
        app: goldenpay
        name: __service
        tier: be
        version: v1
    spec:
      containers:
        - name: goldenpay-__service
          image: chientt1993/goldenpay-be-__service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: __service
spec:
  hosts:
  - __service
  http:
  - match:
    - port: 5000
    route:
    - destination:
        host: __service
        subset: v1

---
# DestinationRule
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: __service
spec:
  host: __service
  subsets:
  - name: v1
    labels:
      version: v1