apiVersion: v1
kind: Service

metadata:
  name: chat
  annotations:
    goldenpay.prometheus/scrape: "true"
    goldenpay.prometheus/path: "/metrics"
    goldenpay.prometheus/port: "5050"
spec:
  ports:
    - port: 5000
      name: grpc
    - port: 5050
      name: metric
  selector:
    app: goldenpay
    name: chat
#  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldenpay-be-deployment-chat
  labels:
    app: goldenpay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goldenpay
      tier: be
  template:
    metadata:
      annotations:
        inject.istio.io/templates: grpc-agent
        proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'
      labels:
        app: goldenpay
        name: chat
        tier: be
        version: v1
    spec:
      containers:
        - name: goldenpay-chat
          image: chientt1993/goldenpay-be-chat
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: chat
spec:
  hosts:
  - chat
  http:
  - match:
    - port: 5000
    route:
    - destination:
        host: chat
        subset: v1

---
# DestinationRule
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: chat
spec:
  host: chat
  subsets:
  - name: v1
    labels:
      version: v1